with-expecter: true
mock-build-tags: "!compile"
inpackage: true
filename: "{{.InterfaceName}}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
packages:
  github.com/ksysoev/oneway/pkg/core/network:
    interfaces:
      Conn:
        inpackage: true
  github.com/ksysoev/oneway/pkg/core/exchange:
    interfaces:
      RevProxyRepo:
        inpackage: true
      ConnectionQueue:
        inpackage: true
  github.com/ksysoev/oneway/pkg/prov/bridge:
    interfaces:
      Connector:
        inpackage: true
      ContextDialer:
        inpackage: true
