services:
  exchange:
    image: golang:1.23
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - MANAGE_API=:9090
      - CONNECTION_API=:9091
      - PROXY_SERVER=:1080
    ports:
      - "9090"
      - "9091"
      - "1080:1080"
    command: >
      go run /app/cmd/oneway/main.go exchange
  revproxy:
    image: golang:1.23
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - EXCHANGE_MANAGE_API=exchange:9090
      - EXCHANGE_CONNECTION_API=exchange:9091
      - SERVICE_NAME1=echoserver
      - SERVICE_ADDRESS1=echoserver:9090
      - SERVICE_NAME2=restapi
      - SERVICE_ADDRESS2=httpserver:8080
      - NAMESPACE=example
    command: >
      go run /app/cmd/oneway/main.go revproxy
    depends_on:
      - exchange
  prometheus:
    image: prom/prometheus
    volumes:
      - "./runtime/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    depends_on:
      - exchange
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "4318:4318"
  echoserver:
    image: golang:1.23
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - GRPC_LISTEN=:9090
    command: >
      go run /app/example/echoserver/main.go
    depends_on:
      - revproxy
  httpserver:
    image: golang:1.23
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - HTTP_LISTEN=:8080
    command: >
      go run /app/example/restapi/main.go
    depends_on:
      - revproxy
