exchange:
  ctrl_api:
    listen: ":9090"
  conn_api: 
    listen: ":9091"
  proxy_server:
    listen: ":1080"
revproxy:
  service:
    namespace: example
    ctrl_api: "exchange:9090"
    services:
      - name: echoserver
        address: "echoserver:9090"
      - name: restapi
        address: "httpserver:8080"
  conn_api:
    address: "exchange:9091"
  

otel:
  service_name: oneway
  meter:
    listen: ":8080"
    path: "/metrics"
